CREATE TABLE IF NOT EXISTS ACTIVE_CHAT (
    ID SERIAL PRIMARY KEY NOT NULL,
    CHAT_ID INTEGER NOT NULL
);

CREATE TABLE IF NOT EXISTS INCOMES (
    ID SERIAL PRIMARY KEY NOT NULL,
    CHAT_ID INTEGER NOT NULL,
    INCOME NUMERIC
);

CREATE TABLE IF NOT EXISTS SPEND (
    ID SERIAL PRIMARY KEY NOT NULL,
    CHAT_ID INTEGER NOT NULL,
    SPEND NUMERIC
)